name = "phoenixnet-portfolio"
compatibility_date = "2024-02-01"

[build]
command = "npm run pages:build"

[site]
bucket = ".vercel/output/static"

[env.production]
name = "phoenixnet-portfolio-production"
routes = [
  { pattern = "phoenixnet.tech/*", zone_name = "phoenixnet.tech" }
]

[env.staging]
name = "phoenixnet-portfolio-staging"
routes = [
  { pattern = "staging.phoenixnet.tech/*", zone_name = "phoenixnet.tech" }
] 